# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0e237097bd1358baa8c0d8b83a8f933"
name = "bAInners – AI Image Banners"
application_url = "https://app-bainners.orivisdev.shop"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "product-test-9.myshopify.com"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_files,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://app-bainners.orivisdev.shop/auth/callback",
  "https://app-bainners.orivisdev.shop/auth/shopify/callback",
  "https://app-bainners.orivisdev.shop/api/auth",
  "https://app-bainners.orivisdev.shop/api/auth/callback"
]

[app_proxy]
prefix = "apps"
subpath = "bainners"
url = "https://app-bainners.orivisdev.shop"
