-- AlterTable
ALTER TABLE `Banner` ADD COLUMN `announcementAnimation` VARCHAR(20) NULL,
    ADD COLUMN `announcementClosable` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `announcementCloseColor` VARCHAR(20) NULL,
    ADD COLUMN `announcementMarquee` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `bannerBackgroundColor` VARCHAR(20) NULL,
    ADD COLUMN `countdownBackgroundColor` VARCHAR(20) NULL,
    ADD COLUMN `countdownStyle` VARCHAR(20) NULL,
    ADD COLUMN `countdownTextColor` VARCHAR(20) NULL,
    ADD COLUMN `ctaBackgroundColor` VARCHAR(20) NULL,
    ADD COLUMN `ctaBorderColor` VARCHAR(20) NULL,
    ADD COLUMN `ctaBordered` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `ctaRounded` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `ctaShadow` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `ctaTextColor` VARCHAR(20) NULL,
    ADD COLUMN `descriptionColor` VARCHAR(20) NULL,
    ADD COLUMN `descriptionFontSize` VARCHAR(20) NULL,
    ADD COLUMN `sliderArrowColor` VARCHAR(20) NULL,
    ADD COLUMN `sliderArrowStyle` VARCHAR(20) NULL,
    ADD COLUMN `sliderBulletColor` VARCHAR(20) NULL,
    ADD COLUMN `titleColor` VARCHAR(20) NULL,
    ADD COLUMN `titleFontSize` VARCHAR(20) NULL;
